version: '2'
services:
  mysql:
      image: mysql:8.0
      container_name: ${MYSQL_HOST}
      env_file:
        - .env
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - USER=${USER}
        - PASSWORD=${PASSWORD}
      ports:
        - 33006:3306
      volumes: 
        - ./data/db/mysql:/var/lib/mysql
        - ./docs:/docs
      command: mysqld --sql_mode=""
      networks:
        - edu-shared

networks:
  edu-shared:
    external: true